import { describe, it, before, after } from 'node:test';
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { mkdtempSync, mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { generatedTargets, isGenerated } from '../hooks/lib/generated-paths.mjs';

const GUARD = fileURLToPath(new URL('../hooks/edit-guard.mjs', import.meta.url));

describe('isGenerated', () => {
  it('matches generated directories and files', () => {
    for (const path of [
      '.claude/rules/style-guide.md',
      '.claude/skills/x/SKILL.md',
      '.cursor/rules/a.mdc',
      '.kiro/steering/a.md',
      '.kiro/hooks/rulesync.json',
      '.mcp.json',
      'CLAUDE.md',
    ]) {
      assert.equal(isGenerated(path), true, path);
    }
  });

  it('leaves hand-owned files alone', () => {
    for (const path of [
      '.claude/settings.json',
      '.claude/plans/p.md',
      '.cursor/plans/c.plan.md',
      '.kiro/specs/x/tasks.md',
      '.kiro/hooks/my-hook.json',
      '.rulesync/rules/a.md',
      'AGENTS.md',
      'src/CLAUDE.md',
    ]) {
      assert.equal(isGenerated(path), false, path);
    }
  });

  it('honours extra paths from the project config', () => {
    assert.equal(isGenerated('docs/generated/a.md', ['docs/generated/']), true);
    assert.equal(isGenerated('GEMINI.md', ['GEMINI.md']), true);
  });
});

describe('generatedTargets', () => {
  it('resolves absolute paths against the root and ignores paths outside it', () => {
    const root = join(tmpdir(), 'proj');
    const inside = join(root, '.claude', 'rules', 'a.md');
    const outside = join(tmpdir(), 'other', '.claude', 'rules', 'a.md');
    assert.deepEqual(generatedTargets([inside, outside, './.mcp.json'], root), ['.claude/rules/a.md', '.mcp.json']);
  });
});

describe('edit-guard.mjs', () => {
  let root;

  before(() => {
    root = mkdtempSync(join(tmpdir(), 'harness-guard-'));
    spawnSync('git', ['init', '-q'], { cwd: root });
    mkdirSync(join(root, '.rulesync'));
    writeFileSync(join(root, '.rulesync', 'harness.json'), JSON.stringify({ syncCommand: 'npm run sync-it' }));
  });

  after(() => rmSync(root, { recursive: true, force: true }));

  const run = (ide, filePath) =>
    spawnSync(process.execPath, [GUARD, ide], {
      cwd: root,
      input: JSON.stringify({ cwd: root, tool_name: 'Write', tool_input: { file_path: join(root, filePath) } }),
      encoding: 'utf8',
    });

  it('blocks Claude with exit 2 and the reason on stderr', () => {
    const result = run('claude', '.claude/rules/a.md');
    assert.equal(result.status, 2);
    assert.match(result.stderr, /`\.claude\/rules\/a\.md` is generated by rulesync/);
    assert.match(result.stderr, /npm run sync-it/);
  });

  it('blocks Kiro with a non-zero exit and the reason on stderr', () => {
    const result = run('kiro', '.kiro/steering/a.md');
    assert.notEqual(result.status, 0);
    assert.match(result.stderr, /generated by rulesync/);
  });

  it('answers Cursor with a JSON deny, and an explicit allow otherwise', () => {
    const denied = run('cursor', '.cursor/rules/a.mdc');
    assert.equal(denied.status, 0);
    const reply = JSON.parse(denied.stdout);
    assert.equal(reply.permission, 'deny');
    assert.match(reply.agent_message, /generated by rulesync/);

    const allowed = run('cursor', 'src/a.ts');
    assert.deepEqual(JSON.parse(allowed.stdout), { permission: 'allow' });
  });

  it('allows ordinary files silently', () => {
    const result = run('claude', 'src/a.ts');
    assert.equal(result.status, 0);
    assert.equal(result.stdout, '');
  });

  it('fails open on an unreadable payload', () => {
    const result = spawnSync(process.execPath, [GUARD, 'claude'], { cwd: root, input: 'not json', encoding: 'utf8' });
    assert.equal(result.status, 0);
  });
});
