/**
 * The files rulesync generates, so the edit guard can stop the agent from editing them.
 *
 * With `delete: true` in rulesync.jsonc every file in these directories is generated
 * (anything else is swept as an orphan), so a directory match is exact. Deliberately
 * absent: `.claude/settings.json` (rulesync owns only its `hooks` key), the plan and
 * spec folders, and `AGENTS.md`, which projects may write by hand.
 */

import { isAbsolute, relative } from 'node:path';

export const GENERATED_DIRS = [
  '.claude/rules/',
  '.claude/skills/',
  '.claude/agents/',
  '.claude/commands/',
  '.cursor/rules/',
  '.cursor/skills/',
  '.cursor/agents/',
  '.cursor/commands/',
  '.kiro/steering/',
  '.kiro/skills/',
  '.kiro/agents/',
  '.kiro/prompts/',
];

export const GENERATED_FILES = [
  'CLAUDE.md',
  '.mcp.json',
  '.cursor/mcp.json',
  '.cursor/hooks.json',
  '.kiro/settings/mcp.json',
  '.kiro/hooks/rulesync.json',
];

/** `path` relative to `root` with forward slashes, or null when it lies outside the project. */
function projectRelative(path, root) {
  const rel = (isAbsolute(path) ? relative(root, path) : path).replace(/\\/g, '/').replace(/^\.\//, '');
  return rel.startsWith('../') || rel === '..' || isAbsolute(rel) ? null : rel;
}

/** True when `relPath` (project-relative, forward slashes) is a generated file. */
export function isGenerated(relPath, extraPaths = []) {
  const lower = relPath.toLowerCase();
  const prefixes = [...GENERATED_DIRS, ...extraPaths.filter((p) => p.endsWith('/'))];
  const exact = [...GENERATED_FILES, ...extraPaths.filter((p) => !p.endsWith('/'))];
  return (
    prefixes.some((prefix) => lower.startsWith(prefix.toLowerCase())) ||
    exact.some((file) => lower === file.toLowerCase())
  );
}

/** The project-relative paths among `paths` that are generated. */
export function generatedTargets(paths, root, extraPaths = []) {
  return [
    ...new Set(
      paths
        .map((path) => projectRelative(path, root))
        .filter((rel) => rel !== null && isGenerated(rel, extraPaths)),
    ),
  ];
}

/** What the agent is told when an edit is blocked. */
export function guardMessage(paths, syncCommand) {
  const list = paths.map((p) => `\`${p}\``).join(', ');
  return `${list} ${paths.length === 1 ? 'is' : 'are'} generated by rulesync, so a direct edit is overwritten on the next sync. Make the change in the source instead: the "> Source:" line at the top of the file names it (project files live in \`.rulesync/\`, shared ones in the agent-harness repo). Then run \`${syncCommand}\`. A new rule or skill belongs in \`.rulesync/\` too; one that already exists only in an IDE folder can be moved there with \`npx agent-harness adopt <path>\`.`;
}
